In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

In [2]:
import os
os.getcwd()

'C:\\Users\\hp'

In [3]:
df=pd.read_csv(r"C:\Users\hp\OneDrive\Scans\Housing price prediction\bengaluru_house_prices.csv")

In [4]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [7]:
df['balcony'].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [8]:
df.drop(columns=['area_type','availability','society'],inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   balcony     12711 non-null  float64
 5   price       13320 non-null  float64
dtypes: float64(3), object(3)
memory usage: 624.5+ KB

In [10]:
df['size']=df['size'].fillna('2 BHK')

In [11]:
df['bath']=df['bath'].fillna(df['bath'].median())

In [12]:
df.drop(columns=['balcony'],inplace=True)

In [13]:
df['BHK']=df['size'].str.split().str.get(0).astype(int)

In [14]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [15]:
import pandas as pd

def convert_range(x):
    if pd.isna(x):
        return None

    elif '-' in str(x):
        temp = x.split('-')
        return (float(temp[0]) + float(temp[1])) / 2

    else:
        try:
            return float(x)
        except:
            return None  #for string it returns none and gets stored as NaN

In [16]:
df['total_sqft']=df['total_sqft'].apply(convert_range)

In [17]:
df['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ], shape=(2000,))

In [18]:
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

In [19]:
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [20]:
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [21]:
df['location'].isnull().sum()

np.int64(1)

In [22]:
df['location'] = df['location'].apply(
    lambda x: x.strip() if isinstance(x, str) else x
)

In [23]:
location_counts=df['location'].value_counts()

In [24]:
location_counts = df['location'].value_counts()

df['location'] = df['location'].apply(
    lambda x: 'Other' if pd.isna(x) or location_counts.get(x, 0) < 10 else x
)

In [25]:
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [26]:
df=df[((df['total_sqft']/df['BHK'])>=300)]

In [27]:
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [28]:
df.shape

(12530, 7)

In [29]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf['price_per_sqft']) # Mean
        st = np.std(subdf['price_per_sqft']) # Standard Deviation
        reduced_df = subdf[(subdf['price_per_sqft'] > (m - st)) & (subdf['price_per_sqft'] <= (m + st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    return df_out

df = remove_pps_outliers(df)
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  10282.000000  10282.000000  10282.000000  10282.000000    10282.000000
mean    1509.996956      2.474032     91.718675      2.576347     5669.007067
std      883.210082      0.986908     88.327858      0.900592     2292.794131
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4249.917219
50%     1286.000000      2.000000     67.000000      2.000000     5176.565008
75%     1650.000000      3.000000    100.000000      3.000000     6431.808627
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [30]:
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        # Step A: Calculate stats for each BHK type in this location
        for bhk, bhk_df in location_df.groupby('BHK'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df['price_per_sqft']),
                'std': np.std(bhk_df['price_per_sqft']),
                'count': bhk_df.shape[0]
            }
        # Step B: Exclude rows where price_per_sqft is less than the mean of a lower BHK
        for bhk, bhk_df in location_df.groupby('BHK'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df['price_per_sqft'] < stats['mean']].index.values)
                
    return df.drop(exclude_indices, axis='index')

df= remove_bhk_outliers(df)

In [31]:
df.shape

(7402, 7)

In [32]:
df.drop(columns=['size','price_per_sqft'],inplace=True)

In [33]:
df

                  location  total_sqft  bath  price  BHK
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10271         Yeshwanthpur      1195.0   2.0  100.0    2
10272         Yeshwanthpur      1692.0   3.0  108.0    3
10274         Yeshwanthpur      2500.0   5.0  185.0    6
10279         Yeshwanthpur      1855.0   3.0  135.0    3
10280         Yeshwanthpur      1876.0   3.0  160.0    3

[7402 rows x 5 columns]

In [34]:
 df.to_csv('Cleaned_data.csv')

In [35]:
x=df.drop(columns=['price'])
y=df['price']

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [37]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [38]:
print(x_train.shape)
print(x_test.shape)

(5921, 4)
(1481, 4)

In [39]:
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

col_trans = make_column_transformer((OneHotEncoder(sparse_output=False), ['location']),remainder='passthrough')

scaler = StandardScaler()

lr = LinearRegression()

pipe = make_pipeline(col_trans, scaler,lr)

In [40]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [41]:
pipe.fit(x_train,y_train)
y_pred_lr = pipe.predict(x_test)
print(r2_score(y_test,y_pred_lr))

0.9001631155301935

In [42]:
lasso=Lasso()
pipe = make_pipeline(col_trans, scaler,lasso)
pipe.fit(x_train,y_train)
y_pred_lasso=pipe.predict(x_test)
r2_score(y_test,y_pred_lasso)

0.8892982225627151

In [43]:
ridge=Ridge()
pipe=make_pipeline(col_trans,scaler,ridge)
pipe.fit(x_train,y_train)
y_pred_ridge=pipe.predict(x_test)
print(r2_score(y_test,y_pred_ridge))

0.9001646231937975

In [44]:
import pickle

In [45]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))

In [46]:
import os
print(os.getcwd())

C:\Users\hp

In [47]:
print(df["location"].unique())

['1st Block Jayanagar' '1st Block Koramangala' '1st Phase JP Nagar'
 '2nd Phase Judicial Layout' '2nd Stage Nagarbhavi' '5th Block Hbr Layout'
 '5th Phase JP Nagar' '6th Phase JP Nagar' '7th Phase JP Nagar'
 '8th Phase JP Nagar' '9th Phase JP Nagar' 'AECS Layout' 'Abbigere'
 'Akshaya Nagar' 'Ambalipura' 'Ambedkar Nagar' 'Amruthahalli' 'Anandapura'
 'Ananth Nagar' 'Anekal' 'Anjanapura' 'Ardendale' 'Arekere' 'Attibele'
 'BEML Layout' 'BTM 1st Stage' 'BTM 2nd Stage' 'BTM Layout' 'Babusapalaya'
 'Badavala Nagar' 'Balagere' 'Banashankari' 'Banashankari Stage II'
 'Banashankari Stage III' 'Banashankari Stage V' 'Banashankari Stage VI'
 'Banaswadi' 'Banjara Layout' 'Bannerghatta' 'Bannerghatta Road'
 'Basapura' 'Basavangudi' 'Basaveshwara Nagar' 'Battarahalli' 'Begur'
 'Begur Road' 'Bellandur' 'Benson Town' 'Bharathi Nagar' 'Bhoganhalli'
 'Billekahalli' 'Binny Pete' 'Bisuvanahalli' 'Bommanahalli' 'Bommasandra'
 'Bommasandra Industrial Area' 'Bommenahalli' 'Brookefield' 'Budigere'
 'CV Raman Nagar' 'Chamrajpet' 'Chandapura' 'Channasandra'
 'Chikka Tirupathi' 'Chikkabanavar' 'Chikkalasandra' 'Choodasandra'
 'Cooke Town' 'Cox Town' 'Cunningham Road' 'Dairy Circle' 'Dasanapura'
 'Dasarahalli' 'Devanahalli' 'Devarachikkanahalli' 'Dodda Nekkundi'
 'Doddaballapur' 'Doddakallasandra' 'Doddathoguru' 'Dodsworth Layout'
 'Domlur' 'Dommasandra' 'EPIP Zone' 'Electronic City'
 'Electronic City Phase II' 'Electronics City Phase 1' 'Frazer Town'
 'GM Palaya' 'Ganga Nagar' 'Garudachar Palya' 'Giri Nagar'
 'Gollarapalya Hosahalli' 'Gottigere' 'Green Glen Layout' 'Gubbalala'
 'Gunjur' 'Gunjur Palya' 'HAL 2nd Stage' 'HBR Layout' 'HRBR Layout'
 'HSR Layout' 'Haralur Road' 'Harlur' 'Hebbal' 'Hebbal Kempapura'
 'Hegde Nagar' 'Hennur' 'Hennur Road' 'Hoodi' 'Horamavu Agara'
 'Horamavu Banaswadi' 'Hormavu' 'Hosa Road' 'Hosakerehalli' 'Hoskote'
 'Hosur Road' 'Hulimavu' 'ISRO Layout' 'ITPL' 'Iblur Village'
 'Indira Nagar' 'JP Nagar' 'Jakkur' 'Jalahalli' 'Jalahalli East' 'Jigani'
 'Judicial Layout' 'KR Puram' 'Kadubeesanahalli' 'Kadugodi'
 'Kaggadasapura' 'Kaggalipura' 'Kaikondrahalli' 'Kalena Agrahara'
 'Kalkere' 'Kalyan nagar' 'Kambipura' 'Kammanahalli' 'Kammasandra'
 'Kanakapura' 'Kanakpura Road' 'Kannamangala' 'Karuna Nagar'
 'Kasavanhalli' 'Kasturi Nagar' 'Kathriguppe' 'Kaval Byrasandra'
 'Kenchenahalli' 'Kengeri' 'Kengeri Satellite Town' 'Kereguddadahalli'
 'Kodichikkanahalli' 'Kodigehaali' 'Kodigehalli' 'Kodihalli' 'Kogilu'
 'Konanakunte' 'Koramangala' 'Kothannur' 'Kothanur' 'Kudlu' 'Kudlu Gate'
 'Kumaraswami Layout' 'Kundalahalli' 'LB Shastri Nagar' 'Laggere'
 'Lakshminarayana Pura' 'Lingadheeranahalli' 'Magadi Road' 'Mahadevpura'
 'Mahalakshmi Layout' 'Mallasandra' 'Malleshpalya' 'Malleshwaram'
 'Marathahalli' 'Margondanahalli' 'Marsur' 'Mico Layout' 'Munnekollal'
 'Murugeshpalya' 'Mysore Road' 'NGR Layout' 'NRI Layout' 'Nagadevanahalli'
 'Naganathapura' 'Nagappa Reddy Layout' 'Nagarbhavi' 'Nagasandra'
 'Nagavara' 'Nagavarapalya' 'Narayanapura' 'Neeladri Nagar' 'Nehru Nagar'
 'OMBR Layout' 'Old Airport Road' 'Old Madras Road' 'Other'
 'Padmanabhanagar' 'Pai Layout' 'Panathur' 'Parappana Agrahara'
 'Pattandur Agrahara' 'Poorna Pragna Layout' 'Prithvi Layout' 'R.T. Nagar'
 'Rachenahalli' 'Raja Rajeshwari Nagar' 'Rajaji Nagar' 'Rajiv Nagar'
 'Ramagondanahalli' 'Ramamurthy Nagar' 'Rayasandra' 'Sadashiva Nagar'
 'Sahakara Nagar' 'Sanjay nagar' 'Sarakki Nagar' 'Sarjapur'
 'Sarjapur  Road' 'Sarjapura - Attibele Road' 'Sector 1 HSR Layout'
 'Sector 2 HSR Layout' 'Sector 7 HSR Layout' 'Seegehalli' 'Shampura'
 'Shivaji Nagar' 'Singasandra' 'Somasundara Palya' 'Sompura'
 'Sonnenahalli' 'Subramanyapura' 'Sultan Palaya' 'TC Palaya'
 'Talaghattapura' 'Thanisandra' 'Thigalarapalya' 'Thubarahalli'
 'Thyagaraja Nagar' 'Tindlu' 'Tumkur Road' 'Ulsoor' 'Uttarahalli'
 'Varthur' 'Varthur Road' 'Vasanthapura' 'Vidyaranyapura' 'Vijayanagar'
 'Vishveshwarya Layout' 'Vishwapriya Layout' 'Vittasandra' 'Whitefield'
 'Yelachenahalli' 'Yelahanka' 'Yelahanka New Town' 'Yelenahalli'
 'Yeshwanthpur']